export const mockModels = [
  {
    id: "1",
    title: "Gear Assembly",
    description: "A detailed 3D model of a complex gear assembly system",
    category: "Machine and Machine Tools",
    thumbnail: "/models/gear-assembly-thumb.png",
    fileUrl: "/models/gear-assembly.stl",
    likes: 245,
    downloads: 189,
    status: "PUBLIC",
  },
  {
    id: "2",
    title: "Heat Exchanger",
    description: "Detailed model of a shell and tube heat exchanger",
    category: "Thermodynamics",
    thumbnail: "/models/heat-exchanger-thumb.png",
    fileUrl: "/models/heat-exchanger.stl",
    likes: 178,
    downloads: 134,
    status: "PUBLIC",
  },
  {
    id: "3",
    title: "Four-Bar Mechanism",
    description: "Interactive model of a four-bar linkage mechanism",
    category: "Theory of Machines",
    thumbnail: "/models/four-bar-thumb.png",
    fileUrl: "/models/four-bar.stl",
    likes: 312,
    downloads: 256,
    status: "PUBLIC",
  },
  {
    id: "4",
    title: "CNC Machine Components",
    description: "Detailed model of CNC machine parts",
    category: "Manufacturing Technology",
    thumbnail: "/models/cnc-thumb.png",
    fileUrl: "/models/cnc.stl",
    likes: 198,
    downloads: 145,
    status: "PUBLIC",
  },
  {
    id: "5",
    title: "Engine Piston Assembly",
    description: "Complete piston assembly with all components",
    category: "Solid Modeling",
    thumbnail: "/models/piston-thumb.png",
    fileUrl: "/models/piston.stl",
    likes: 267,
    downloads: 201,
    status: "PUBLIC",
  },
];

export const mockReviews = [
  {
    id: "1",
    quote: "This platform has revolutionized how I learn engineering concepts. The 3D models are incredibly detailed!",
    name: "Dr. Sarah Chen",
    title: "Professor of Mechanical Engineering",
  },
  {
    id: "2",
    quote: "As a student, having access to these interactive 3D models has made complex mechanisms much easier to understand.",
    name: "Michael Rodriguez",
    title: "Engineering Student",
  },
  {
    id: "3",
    quote: "The quality of models and the community support is outstanding. A must-have resource for engineering education.",
    name: "Prof. James Wilson",
    title: "Department Head, Engineering",
  },
  {
    id: "4",
    quote: "The platform's interface is intuitive, and the model collection is comprehensive. Great for both teaching and learning.",
    name: "Dr. Emily Thompson",
    title: "Engineering Researcher",
  },
  {
    id: "5",
    quote: "Being able to manipulate and study 3D models has significantly improved my understanding of mechanical systems.",
    name: "Alex Kumar",
    title: "Graduate Student",
  },
]; 